/**
 * warning: this file is generated by tarat. do not modified this file
 */
import React from "react";
import { Routes, Route } from "react-router-dom";
import { StaticRouter } from "react-router-dom/server.js";

import Main from "/Users/yunge/Documents/tarat/packages/example/markdown-editor/app/pages/main.jsx";

export default function App({ location }) {
  return (
    <StaticRouter>
      <Routes location={location}>
        <Route path="main" element={<Main />}></Route>
      </Routes>
    </StaticRouter>
  );
}
