export const injectTagStart = '/**. auto generated by tarat */'
export const injectTagEnd = '/** auto generated by tarat .*/'

export const autoGeneratedFileTag = '@@tarat generated file'

export const autoGeneratedTip = () => [
  '//',
  `// ${autoGeneratedFileTag}`,
  '// provide by @tarat',
  '// warning: auto generated by tarat.do not modifed this file',
  '//'
]

