export const injectTagStart = '/*--tarat deps start--*/'
export const injectTagEnd = '/*--tarat deps end--*/'

export const autoGeneratedFileTag = '@@tarat generated file'

export const autoGeneratedTip = () => [
  '//',
  `// ${autoGeneratedFileTag}`,
  '// provide by @tarat',
  '// warning: auto generated by tarat.do not modifed this file',
  '//'
]

