import {
  after,
  combineLatest,
  computed,
  inputCompute,
  inputComputeInServer,
  model,
  state,
} from "tarat-core";

export default function mdEditor(q = {}) {
  const currentId = state(q.id);
  const inputMD = state("");

  const currentPost = model("markdown", () => {
    const cid = currentId();
    if (cid) {
      return {
        where: {
          id: cid,
        },
      };
    }
  });

  const postedMD = computed(() => {
    return currentPost()[0]?.content;
  });

  const displayMD = combineLatest([inputMD, postedMD]);

  const save = inputComputeInServer(async () => {
    const cid = currentId();
    if (cid) {
      if (currentPost()[0]) {
        currentPost((arr) => {
          arr[0].content = inputMD();
        });
      }
    } else {
      const r = await currentPost.create({
        content: inputMD(),
      });
      currentId(() => r.id);
    }
  });

  after(() => {}, [currentPost]);

  return {
    displayMD,
    postedMD,
    inputMD,
    save,
  };
}

/**. auto generated by tarat */
const autoParser = {
  mdEditor: {
    names: [
      [0, "currentId"],
      [1, "inputMD"],
      [2, "currentPost"],
      [3, "postedMD"],
      [4, "save"],
    ],
    deps: [
      ["h", 2, [0]],
      ["h", 3, [2]],
      ["h", 4, [0, 2, 1], [2, 0]],
    ],
  },
};
Object.assign(mdEditor, {
  __deps__: autoParser.mdEditor.deps,
  __names__: autoParser.mdEditor.names,
  __name__: "mdEditor",
});
/** auto generated by tarat .*/
