import {
  after,
  combineLatest,
  computed,
  inputCompute,
  inputComputeInServer,
  model,
  state,
  writeModel,
} from "tarat-core";

export default function mdEditor(q = {}) {
  const currentId = state(q.id);
  const inputMD = state("");
  const inputTitle = state("");

  const currentPost = model("markdown", () => {
    const cid = currentId();
    if (cid) {
      return {
        where: {
          id: cid,
        },
      };
    }
  });

  const markdownTitle = computed(() => {
    return currentPost()[0]?.title;
  });

  const postedMD = computed(() => {
    return currentPost()[0]?.content;
  });

  const displayMD = combineLatest([inputMD, postedMD]);
  const displayTitle = combineLatest([inputTitle, markdownTitle]);

  const writeCurrentMD = writeModel(currentPost, () => ({
    title: inputTitle() || displayTitle(),
    content: inputMD() || displayMD(),
  }));

  const save = inputComputeInServer(async () => {
    const cid = currentId();
    if (cid) {
      /** @TODO should analyze corect deps */
      writeCurrentMD.update(cid);
    }
  });

  return {
    displayMD,
    postedMD,
    inputMD,
    inputTitle,
    displayTitle,
    save,
  };
}

/**. auto generated by tarat */
const autoParser = {
  mdEditor: {
    names: [
      [0, "currentId"],
      [1, "inputMD"],
      [2, "inputTitle"],
      [3, "currentPost"],
      [4, "markdownTitle"],
      [5, "postedMD"],
      [6, "writeCurrentMD"],
      [7, "save"],
    ],
    deps: [
      ["h", 3, [0]],
      ["h", 4, [3]],
      ["h", 5, [3]],
      ["h", 6, [3, 2, 1], [3, 2, 1]],
      ["h", 7, [0], [6]],
    ],
  },
};
Object.assign(mdEditor, {
  __deps__: autoParser.mdEditor.deps,
  __names__: autoParser.mdEditor.names,
  __name__: "mdEditor",
});
/** auto generated by tarat .*/
