import {
  combineLatest,
  compose,
  inputCompute,
  inputComputeInServer,
  prisma,
  state,
  writePrisma,
} from "tarat-core";

import rename from "./rename";

export interface Folder {
  id?: number;
  name: string;
  rm: boolean;
  items: FolderItem[];
}

export interface FolderItem {
  id?: number;
  name: string;
  folderId?: number;
}

const INITIAL_FOLDER_NAME = "新建文件夹";
const INITIAL_ITEM_NAME = "新建文件";

export enum ETypes {
  folder = "folder",
  item = "item",
}

function cascading() {
  const folders = prisma<Folder[]>("folder", () => ({}));

  const renameFolderCompose = compose(rename);

  const folderName = state(INITIAL_FOLDER_NAME);

  const createOrUpdateFolers = writePrisma(folders, () => ({
    name: folderName(),
  }));

  const removeFolders = writePrisma(folders, () => ({
    rm: true,
  }));

  const createFolder = inputComputeInServer(function* () {
    yield createOrUpdateFolers.create();
    folderName(() => INITIAL_FOLDER_NAME);
  });

  const updateFolder = inputComputeInServer(function* () {
    yield createOrUpdateFolers.update(renameFolderCompose.currentId());
    folderName(() => INITIAL_FOLDER_NAME);
  });

  const removeFolder = inputComputeInServer(function* (folder?: Folder) {
    yield removeFolders.remove(folder.id || renameFolderCompose.currentId());
    renameFolderCompose.currentId(() => folders()[0]?.id);
  });

  const renameFolder = inputComputeInServer(function* () {
    const input = renameFolderCompose.renameInput();
    if (input.id) {
      folderName(() => input.name);
      yield updateFolder();
      renameFolderCompose.endRename();
    }
  });

  const items = prisma<FolderItem[]>("item", () => {
    const fid = renameFolderCompose.currentId();
    if (fid) {
      return {
        where: {
          folderId: fid,
        },
      };
    }
  });

  const myItemId = state<number>();

  const renameItemCompose = compose(rename);

  const itemName = state(INITIAL_ITEM_NAME);

  const writeItems = writePrisma(items, () => ({
    folder: {
      connect: {
        id: renameFolderCompose.currentId(),
      },
    },
    name: itemName(),
  }));

  const createItem = inputComputeInServer(function* () {
    yield writeItems.create();
    itemName(() => INITIAL_ITEM_NAME);
  });

  const updateItem = inputComputeInServer(function* () {
    yield writeItems.update(renameItemCompose.currentId());
    itemName(() => INITIAL_ITEM_NAME);
  });

  const removeItem = inputComputeInServer(function* (item?: FolderItem) {
    yield writeItems.remove(item.id || renameItemCompose.currentId());
    myItemId(() => folders()[0]?.id);
  });

  const renameItem = inputComputeInServer(function* () {
    const input = renameItemCompose.renameInput();
    if (input.id) {
      itemName(() => input.name);
      yield updateItem();
      renameItemCompose.endRename();
    }
  });

  const ss = state("");

  return {
    ss,
    // folder
    folders,
    folderName,
    currentFolderId: renameFolderCompose.currentId,
    switchCurrentFolder: renameFolderCompose.switchCurrent,
    createFolder,
    updateFolder,
    removeFolder,
    // folder rename
    renameFolderInput: renameFolderCompose.renameInput,
    startRename: renameFolderCompose.startRename,
    renameFolder,
    // item
    items,
    itemName,
    currentItemId: renameItemCompose.currentId,
    switchCurrentItem: renameItemCompose.switchCurrent,
    createItem,
    updateItem,
    removeItem,
    // item rename
    renameItemInput: renameItemCompose.renameInput,
    startItemRename: renameItemCompose.startRename,
    renameItem,
  };
}

export default cascading;

/**. auto generated by tarat */
const autoParser = {
  cascading: {
    names: [
      [0, "folders"],
      [1, "folderName"],
      [2, "createOrUpdateFolers"],
      [3, "removeFolders"],
      [4, "createFolder"],
      [5, "updateFolder"],
      [6, "removeFolder"],
      [7, "renameFolder"],
      [8, "items"],
      [9, "myItemId"],
      [10, "itemName"],
      [11, "writeItems"],
      [12, "createItem"],
      [13, "updateItem"],
      [14, "removeItem"],
      [15, "renameItem"],
      [16, "ss"],
    ],
    deps: [
      ["h", 2, [0, 1], [0, 1]],
      ["h", 3, [0], [0]],
      ["h", 4, [2], [1]],
      ["h", 5, [["c", 0, "currentId"]], [2, 1]],
      ["h", 6, [["c", 0, "currentId"], 0], [3, ["c", 0, "currentId"]]],
      ["h", 7, [["c", 0, "renameInput"], 5, ["c", 0, "endRename"]], [1]],
      ["h", 8, [["c", 0, "currentId"]]],
      ["h", 11, [8, ["c", 0, "currentId"], 10], [8, 10]],
      ["h", 12, [11], [10]],
      ["h", 13, [["c", 1, "currentId"]], [11, 10]],
      ["h", 14, [["c", 1, "currentId"], 0], [11, 9]],
      ["h", 15, [["c", 1, "renameInput"], 13, ["c", 1, "endRename"]], [10]],
    ],
  },
};
Object.assign(cascading, {
  __deps__: autoParser.cascading.deps,
  __names__: autoParser.cascading.names,
  __name__: "cascading",
});
/** auto generated by tarat .*/
