import {
  inputCompute,
  inputComputeInServer,
  prisma,
  state,
  writePrisma,
} from "tarat-core";

export interface RenameTarget {
  id?: number;
  name: string;
}

function rename() {
  const renameInput = state<RenameTarget>({
    id: undefined,
    name: "",
  });
  const currentId = state<number>();

  const startRename = inputCompute((f: RenameTarget) => {
    renameInput((v) => {
      Object.assign(v, {
        id: f.id,
        name: f.name,
      });
    });
    currentId(() => f.id);
  });

  const switchCurrent = inputCompute((f: RenameTarget) => {
    if (f.id !== currentId()) {
      currentId(() => f.id);
      renameInput((v) => {
        v.id = null;
      });
    }
  });

  const endRename = inputCompute(() => {
    renameInput((v) => {
      v.id = null;
    });
  });

  return {
    currentId,
    renameInput,
    startRename,
    endRename,
    switchCurrent,
  };
}

export default rename;

/**. auto generated by tarat */
const autoParser = {
  rename: {
    names: [
      [0, "renameInput"],
      [1, "currentId"],
      [2, "startRename"],
      [3, "switchCurrent"],
      [4, "endRename"],
    ],
    deps: [
      ["h", 2, [], [0, 1]],
      ["h", 3, [1], [1, 0]],
      ["h", 4, [], [0]],
    ],
  },
};
Object.assign(rename, {
  __deps__: autoParser.rename.deps,
  __names__: autoParser.rename.names,
  __name__: "rename",
});
/** auto generated by tarat .*/
