import {
  inputCompute,
  inputComputeInServer,
  prisma,
  state,
  writePrisma,
} from "tarat-core";

export default function single() {
  const name = state("init");
  return {
    name,
  };
}
/**. auto generated by tarat */
const autoParser = { single: { names: [[0, "name"]], deps: [] } };
Object.assign(single, {
  __deps__: autoParser.single.deps,
  __names__: autoParser.single.names,
  __name__: "single",
});
/** auto generated by tarat .*/
