import { state } from "tarat-core";

export default function todo() {
  const s = state(0);

  return {
    s,
  };
}
/**. auto generated by tarat */
const autoParser = { todo: { names: [[0, "s"]], deps: [] } };
Object.assign(todo, {
  __deps__: autoParser.todo.deps,
  __names__: autoParser.todo.names,
  __name__: "todo",
});
/** auto generated by tarat .*/
