import {
  computed,
  connectModel,
  inputComputeInServer,
  model,
  state,
  writeModel,
  writePrisma,
} from "tarat/core";

export interface ITopic {
  id?: number;
  title: string;
}

export interface ITopicProps {
  id?: number;
}

export default function topic() {
  const topics = model<ITopic[]>("topic", () => ({
    orderBy: {
      createdAt: "desc",
    },
  }));

  const inputName = state("");

  const writeTopics = writePrisma(topics, () => {
    return {
      title: inputName(),
    };
  });

  const add = inputComputeInServer(function* () {
    if (inputName()) {
      yield writeTopics.create();
      inputName(() => "");
    }
  });

  return {
    topics,
    writeTopics,
    add,
    inputName,
  };
}

/**. auto generated by tarat */
const autoParser = {
  topic: {
    names: [
      [0, "topics"],
      [1, "inputName"],
      [2, "writeTopics"],
      [3, "add"],
    ],
    deps: [
      ["h", 2, [0, 1], [0, 1]],
      ["h", 3, [1, 2], [1]],
    ],
  },
};
Object.assign(topic, {
  __deps__: autoParser.topic.deps,
  __names__: autoParser.topic.names,
  __name__: "topic",
});
/** auto generated by tarat .*/
