
//
// @@tarat generated file
// provide by @tarat
// warning: auto generated by tarat.do not modifed this file
//
export { default } from 'tarat-file-uploader/dist/drivers/uploader'
import d from 'tarat-file-uploader/dist/drivers/uploader'
Object.assign(d, { __ })
