# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: doc html website

on:
  push:
    branches: [ master ]
    paths:
      - 'doc/en/**.md'
      - 'scripts/build-doc.js'
  pull_request:
    branches: [ master ]
    paths:
      - 'doc/en/**.md'
      - 'scripts/build-doc.js'

jobs:
  build:
    name: compile doc/en to html
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v2
      with:
        node-version: 16.x
        cache: 'npm'
    - run: npm run build:doc --if-present
    - name: Deploy to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.5
      with:
        branch: master
        folder: .
